### ISSUE TITLE
Deploy no heroku nao funciona

### ISSUE THREAD

**Issue by lucasitz** [tiagocordeiro/gomenu#229]
Localmente o app esta rodando bem, so que quando subo pro heroku retorna um erro...

2021-10-19T21:37:02.252870+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/shlex.py", line 140, in read_token
2021-10-19T21:37:02.252870+00:00 app[web.1]: nextchar = self.instream.read(1)
2021-10-19T21:37:02.252871+00:00 app[web.1]: AttributeError: 'list' object has no attribute 'read'

Uma parte do erro, como resolver isso ?

**Comment by lucasitz** [comment]
Ola @tiagocordeiro , estou fazendo o deploy pelo heroku cli, localmente uso python 3.8 msm, o env esta nessa versao, e verifiquei o runtime msm que a versao e 3.9.7. Tenho entao que usar o 3.9.7 localmente ?

**Comment by tiagocordeiro** [comment]
Ok, não é necessário rodar localmente com python 3.9.7
Verifique se você criou as variáveis necessárias para o projeto na Heroku: no seu projeto, em `Settings > Config Vars`

DISABLE_COLLECTSTATIC: 1
ALLOWED_HOSTS: .herokuapp.com
DATABASE_URL: (vai ser criado automaticamente no deploy)
DEBUG: False
DJANGO_AWS_ACCESS_KEY_ID:
DJANGO_AWS_SECRET_ACCESS_KEY:
DJANGO_AWS_STORAGE_BUCKET_NAME:
SECRET_KEY: (do Django, pode usar o script `contrib/env_gen.py` na raiz do projeto para gerar a key)
SENTRY_DSN:

Você também vai precisar criar um bucket S3 na AWS (https://s3.console.aws.amazon.com) para o staticos e arquivos de mídia e configurar o sentry (https://sentry.io/) para acompanhar os erros.
